SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[Bottles](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[DistilleryId] [int] NOT NULL,
	[Age] [int] NOT NULL,
	[AlcoholByVolume] [real] NOT NULL,
	[WhiskyBaseId] [int] NULL
) ON [PRIMARY]

ALTER TABLE [dbo].[Bottles]  WITH CHECK ADD  CONSTRAINT [FK_Bottles_Distilleries_DistilleryId] FOREIGN KEY([DistilleryId])
REFERENCES [dbo].[Distilleries] ([Id])
ON DELETE CASCADE
ALTER TABLE [dbo].[Bottles] CHECK CONSTRAINT [FK_Bottles_Distilleries_DistilleryId]
CREATE NONCLUSTERED INDEX [IX_Bottles_DistilleryId] ON [dbo].[Bottles]
(
	[DistilleryId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
ALTER TABLE [dbo].[Bottles] ADD  CONSTRAINT [PK_Bottles] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
